modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"

[[mods]]
    modId="mekanismtools"
    version="${file.jarVersion}"
    displayName="Mekanism Tools"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster"
    description='''
      Add tools to Mekanism
      '''