files:
  - source: /src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
    translation: /src/main/resources/assets/mekanism/lang/%locale_with_underscore%.json
  - source: >-
      /src/datagen/generated/mekanismadditions/assets/mekanismadditions/lang/en_us.json
    translation: >-
      /src/additions/resources/assets/mekanismadditions/lang/%locale_with_underscore%.json
  - source: >-
      /src/datagen/generated/mekanismgenerators/assets/mekanismgenerators/lang/en_us.json
    translation: >-
      /src/generators/resources/assets/mekanismgenerators/lang/%locale_with_underscore%,json
  - source: /src/datagen/generated/mekanismtools/assets/mekanismtools/lang/en_us.json
    translation: >-
      /src/tools/resources/assets/mekanismtools/lang/%locale_with_underscore%.json
languages_mapping:
  af_ZA: af_za
  ar_SA: ar_sa
  ast_ES: ast_es
  az_AZ: az_az
  ba_RU: ba_ru
  be_BY: be_by
  bg_BG: bg_bg
  br_FR: br_fr
  bs_BA: bs_ba
  ca_ES: ca_es
  cs_CZ: cs_cz
  cy_GB: cy_gb
  da_DK: da_dk
  de_AT: de_at
  de_CH: de_ch
  de_DE: de_de
  el_GR: el_gr
  en_AU: en_au
  en_CA: en_ca
  en_GB: en_gb
  en_NZ: en_nz
  en_PT: en_pt
  en_US: en_us
  eo_UY: eo_uy
  es_AR: es_ar
  es_CL: es_cl
  es_ES: es_es
  es_MX: es_mx
  es_UY: es_uy
  es_VE: es_ve
  et_EE: et_ee
  eu_ES: eu_es
  fa_IR: fa_ir
  fi_FI: fi_fi
  fil_PH: fil_ph
  fo_FO: fo_fo
  fr_CA: fr_ca
  fr_FR: fr_fr
  fra_DE: fra_de
  fy_NL: fy_nl
  ga_IE: ga_ie
  gd_GB: gd_gb
  gl_ES: gl_es
  got_DE: got_de
  gv_IM: gv_im
  haw_US: haw_us
  he_IL: he_il
  hi_IN: hi_in
  hr_HR: hr_hr
  hu_HU: hu_hu
  hy_AM: hy_am
  id_ID: id_id
  ig_NG: ig_ng
  io_EN: io_en
  is_IS: is_is
  it_IT: it_it
  ja_JP: ja_jp
  jbo_EN: jbo_en
  ka_GE: ka_ge
  kab_KAB: kab_kab
  kk_KZ: kk_kz
  kn_IN: kn_in
  ko_KR: ko_kr
  kw_GB: kw_gb
  la_VA: la_va
  lb_LU: lb_lu
  li_LI: li_li
  lol_US: lol_us
  lt_LT: lt_lt
  lv_LV: lv_lv
  mi_NZ: mi_nz
  mk_MK: mk_mk
  mn_MN: mn_mn
  moh_CA: moh_ca
  ms_MY: ms_my
  mt_MT: mt_mt
  nds_DE: nds_de
  nl_BE: nl_be
  nl_NL: nl_nl
  nn_NO: nn_no
  nb_NO: nb_no
  oc_FR: oc_fr
  oj_CA: oj_ca
  pl_PL: pl_pl
  pt_BR: pt_br
  pt_PT: pt_pt
  qya_AA: qya_aa
  ro_RO: ro_ro
  ru_RU: ru_ru
  sk_SK: sk_sk
  sl_SI: sl_si
  so_SO: so_so
  sq_AL: sq_al
  sr_SP: sr_sp
  sv_SE: sv_se
  ta_IN: ta_in
  th_TH: th_th
  tlh_AA: tlh_aa
  tr_TR: tr_tr
  tt_RU: tt_ru
  tzl_TZL: tzl_tzl
  uk_UA: uk_ua
  val_ES: val_es
  vec_IT: vec_it
  vi_VN: vi_vn
  yi_DE: yi_de
  yo_NG: yo_ng
  zh_CN: zh_cn
  zh_TW: zh_tw
  tl_PH: tl_ph
