files:
  - source: /src/datagen/generated/mekanism/assets/mekanism/lang/en_us.json
    translation: /src/main/resources/assets/mekanism/lang/%locale_with_underscore%.json
    languages-mapping:
      locale_with-underscore:
        af-ZA: af_za
        ar-SA: ar_sa
        ast-ES: ast_es
        az-AZ: az_az
        ba-RU: ba_ru
        be-BY: be_by
        bg-BG: bg_bg
        br-FR: br_fr
        bs-BA: bs_ba
        ca-ES: ca_es
        cs-CZ: cs_cz
        cy-GB: cy_gb
        da-DK: da_dk
        de-AT: de_at
        de-CH: de_ch
        de-DE: de_de
        el-GR: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        eo-UY: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et-EE: et_ee
        eu-ES: eu_es
        fa-IR: fa_ir
        fi-FI: fi_fi
        fil-PH: fil_ph
        fo-FO: fo_fo
        fr-CA: fr_ca
        fr-FR: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd-GB: gd_gb
        gl-ES: gl_es
        got-DE: got_de
        gv-IM: gv_im
        haw-US: haw_us
        he-IL: he_il
        hi-IN: hi_in
        hr-HR: hr_hr
        hu-HU: hu_hu
        hy-AM: hy_am
        id-ID: id_id
        ig-NG: ig_ng
        io-EN: io_en
        is-IS: is_is
        it-IT: it_it
        ja-JP: ja_jp
        jbo-EN: jbo_en
        ka-GE: ka_ge
        kab-KAB: kab_kab
        kk-KZ: kk_kz
        kn-IN: kn_in
        ko-KR: ko_kr
        kw-GB: kw_gb
        la-VA: la_va
        lb-LU: lb_lu
        li-LI: li_li
        lol-US: lol_us
        lt-LT: lt_lt
        lv-LV: lv_lv
        mi-NZ: mi_nz
        mk-MK: mk_mk
        mn-MN: mn_mn
        moh-CA: moh_ca
        ms-MY: ms_my
        mt-MT: mt_mt
        nds-DE: nds_de
        nl-BE: nl_be
        nl-NL: nl_nl
        nn-NO: nn_no
        nb-NO: nb_no
        oc-FR: oc_fr
        oj-CA: oj_ca
        pl-PL: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro-RO: ro_ro
        ru-RU: ru_ru
        sk-SK: sk_sk
        sl-SI: sl_si
        so-SO: so_so
        sq-AL: sq_al
        sr-SP: sr_sp
        sv-SE: sv_se
        ta-IN: ta_in
        th-TH: th_th
        tlh-AA: tlh_aa
        tr-TR: tr_tr
        tt-RU: tt_ru
        tzl-TZL: tzl_tzl
        uk-UA: uk_ua
        val-ES: val_es
        vec-IT: vec_it
        vi-VN: vi_vn
        yi-DE: yi_de
        yo-NG: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
        tl-PH: tl_ph
  - source: >-
      /src/datagen/generated/mekanismadditions/assets/mekanismadditions/lang/en_us.json
    translation: >-
      /src/additions/resources/assets/mekanismadditions/lang/%locale_with_underscore%.json
    languages-mapping:
      locale_with-underscore:
        af-ZA: af_za
        ar-SA: ar_sa
        ast-ES: ast_es
        az-AZ: az_az
        ba-RU: ba_ru
        be-BY: be_by
        bg-BG: bg_bg
        br-FR: br_fr
        bs-BA: bs_ba
        ca-ES: ca_es
        cs-CZ: cs_cz
        cy-GB: cy_gb
        da-DK: da_dk
        de-AT: de_at
        de-CH: de_ch
        de-DE: de_de
        el-GR: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        eo-UY: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et-EE: et_ee
        eu-ES: eu_es
        fa-IR: fa_ir
        fi-FI: fi_fi
        fil-PH: fil_ph
        fo-FO: fo_fo
        fr-CA: fr_ca
        fr-FR: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd-GB: gd_gb
        gl-ES: gl_es
        got-DE: got_de
        gv-IM: gv_im
        haw-US: haw_us
        he-IL: he_il
        hi-IN: hi_in
        hr-HR: hr_hr
        hu-HU: hu_hu
        hy-AM: hy_am
        id-ID: id_id
        ig-NG: ig_ng
        io-EN: io_en
        is-IS: is_is
        it-IT: it_it
        ja-JP: ja_jp
        jbo-EN: jbo_en
        ka-GE: ka_ge
        kab-KAB: kab_kab
        kk-KZ: kk_kz
        kn-IN: kn_in
        ko-KR: ko_kr
        kw-GB: kw_gb
        la-VA: la_va
        lb-LU: lb_lu
        li-LI: li_li
        lol-US: lol_us
        lt-LT: lt_lt
        lv-LV: lv_lv
        mi-NZ: mi_nz
        mk-MK: mk_mk
        mn-MN: mn_mn
        moh-CA: moh_ca
        ms-MY: ms_my
        mt-MT: mt_mt
        nds-DE: nds_de
        nl-BE: nl_be
        nl-NL: nl_nl
        nn-NO: nn_no
        nb-NO: nb_no
        oc-FR: oc_fr
        oj-CA: oj_ca
        pl-PL: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro-RO: ro_ro
        ru-RU: ru_ru
        sk-SK: sk_sk
        sl-SI: sl_si
        so-SO: so_so
        sq-AL: sq_al
        sr-SP: sr_sp
        sv-SE: sv_se
        ta-IN: ta_in
        th-TH: th_th
        tlh-AA: tlh_aa
        tr-TR: tr_tr
        tt-RU: tt_ru
        tzl-TZL: tzl_tzl
        uk-UA: uk_ua
        val-ES: val_es
        vec-IT: vec_it
        vi-VN: vi_vn
        yi-DE: yi_de
        yo-NG: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
        tl-PH: tl_ph
  - source: >-
      /src/datagen/generated/mekanismgenerators/assets/mekanismgenerators/lang/en_us.json
    translation: >-
      /src/generators/resources/assets/mekanismgenerators/lang/%locale_with_underscore%.json
    languages-mapping:
      locale_with-underscore:
        af-ZA: af_za
        ar-SA: ar_sa
        ast-ES: ast_es
        az-AZ: az_az
        ba-RU: ba_ru
        be-BY: be_by
        bg-BG: bg_bg
        br-FR: br_fr
        bs-BA: bs_ba
        ca-ES: ca_es
        cs-CZ: cs_cz
        cy-GB: cy_gb
        da-DK: da_dk
        de-AT: de_at
        de-CH: de_ch
        de-DE: de_de
        el-GR: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        eo-UY: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et-EE: et_ee
        eu-ES: eu_es
        fa-IR: fa_ir
        fi-FI: fi_fi
        fil-PH: fil_ph
        fo-FO: fo_fo
        fr-CA: fr_ca
        fr-FR: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd-GB: gd_gb
        gl-ES: gl_es
        got-DE: got_de
        gv-IM: gv_im
        haw-US: haw_us
        he-IL: he_il
        hi-IN: hi_in
        hr-HR: hr_hr
        hu-HU: hu_hu
        hy-AM: hy_am
        id-ID: id_id
        ig-NG: ig_ng
        io-EN: io_en
        is-IS: is_is
        it-IT: it_it
        ja-JP: ja_jp
        jbo-EN: jbo_en
        ka-GE: ka_ge
        kab-KAB: kab_kab
        kk-KZ: kk_kz
        kn-IN: kn_in
        ko-KR: ko_kr
        kw-GB: kw_gb
        la-VA: la_va
        lb-LU: lb_lu
        li-LI: li_li
        lol-US: lol_us
        lt-LT: lt_lt
        lv-LV: lv_lv
        mi-NZ: mi_nz
        mk-MK: mk_mk
        mn-MN: mn_mn
        moh-CA: moh_ca
        ms-MY: ms_my
        mt-MT: mt_mt
        nds-DE: nds_de
        nl-BE: nl_be
        nl-NL: nl_nl
        nn-NO: nn_no
        nb-NO: nb_no
        oc-FR: oc_fr
        oj-CA: oj_ca
        pl-PL: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro-RO: ro_ro
        ru-RU: ru_ru
        sk-SK: sk_sk
        sl-SI: sl_si
        so-SO: so_so
        sq-AL: sq_al
        sr-SP: sr_sp
        sv-SE: sv_se
        ta-IN: ta_in
        th-TH: th_th
        tlh-AA: tlh_aa
        tr-TR: tr_tr
        tt-RU: tt_ru
        tzl-TZL: tzl_tzl
        uk-UA: uk_ua
        val-ES: val_es
        vec-IT: vec_it
        vi-VN: vi_vn
        yi-DE: yi_de
        yo-NG: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
        tl-PH: tl_ph
  - source: /src/datagen/generated/mekanismtools/assets/mekanismtools/lang/en_us.json
    translation: >-
      /src/tools/resources/assets/mekanismtools/lang/%locale_with_underscore%.json
    languages-mapping:
      locale_with-underscore:
        af-ZA: af_za
        ar-SA: ar_sa
        ast-ES: ast_es
        az-AZ: az_az
        ba-RU: ba_ru
        be-BY: be_by
        bg-BG: bg_bg
        br-FR: br_fr
        bs-BA: bs_ba
        ca-ES: ca_es
        cs-CZ: cs_cz
        cy-GB: cy_gb
        da-DK: da_dk
        de-AT: de_at
        de-CH: de_ch
        de-DE: de_de
        el-GR: el_gr
        en-AU: en_au
        en-CA: en_ca
        en-GB: en_gb
        en-NZ: en_nz
        en-PT: en_pt
        en-US: en_us
        eo-UY: eo_uy
        es-AR: es_ar
        es-CL: es_cl
        es-ES: es_es
        es-MX: es_mx
        es-UY: es_uy
        es-VE: es_ve
        et-EE: et_ee
        eu-ES: eu_es
        fa-IR: fa_ir
        fi-FI: fi_fi
        fil-PH: fil_ph
        fo-FO: fo_fo
        fr-CA: fr_ca
        fr-FR: fr_fr
        fra-DE: fra_de
        fy-NL: fy_nl
        ga-IE: ga_ie
        gd-GB: gd_gb
        gl-ES: gl_es
        got-DE: got_de
        gv-IM: gv_im
        haw-US: haw_us
        he-IL: he_il
        hi-IN: hi_in
        hr-HR: hr_hr
        hu-HU: hu_hu
        hy-AM: hy_am
        id-ID: id_id
        ig-NG: ig_ng
        io-EN: io_en
        is-IS: is_is
        it-IT: it_it
        ja-JP: ja_jp
        jbo-EN: jbo_en
        ka-GE: ka_ge
        kab-KAB: kab_kab
        kk-KZ: kk_kz
        kn-IN: kn_in
        ko-KR: ko_kr
        kw-GB: kw_gb
        la-VA: la_va
        lb-LU: lb_lu
        li-LI: li_li
        lol-US: lol_us
        lt-LT: lt_lt
        lv-LV: lv_lv
        mi-NZ: mi_nz
        mk-MK: mk_mk
        mn-MN: mn_mn
        moh-CA: moh_ca
        ms-MY: ms_my
        mt-MT: mt_mt
        nds-DE: nds_de
        nl-BE: nl_be
        nl-NL: nl_nl
        nn-NO: nn_no
        nb-NO: nb_no
        oc-FR: oc_fr
        oj-CA: oj_ca
        pl-PL: pl_pl
        pt-BR: pt_br
        pt-PT: pt_pt
        qya-AA: qya_aa
        ro-RO: ro_ro
        ru-RU: ru_ru
        sk-SK: sk_sk
        sl-SI: sl_si
        so-SO: so_so
        sq-AL: sq_al
        sr-SP: sr_sp
        sv-SE: sv_se
        ta-IN: ta_in
        th-TH: th_th
        tlh-AA: tlh_aa
        tr-TR: tr_tr
        tt-RU: tt_ru
        tzl-TZL: tzl_tzl
        uk-UA: uk_ua
        val-ES: val_es
        vec-IT: vec_it
        vi-VN: vi_vn
        yi-DE: yi_de
        yo-NG: yo_ng
        zh-CN: zh_cn
        zh-TW: zh_tw
        tl-PH: tl_ph
