modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"

[[mods]]
    modId="mekanismgenerators"
    version="${file.jarVersion}"
    displayName="Mekanism Generators"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster"
    description='''
      Add generators to Mekanism
      '''